security:
    providers:
        short_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: '^/'
            guard:
                authenticators:
                    - App\Security\Guard\ApacheModAuthMellonGuardAuthenticator
            anonymous: true
            switch_user: true

    access_control:
        - { path: '^/manage', role: 'ROLE_USER' }
        - { path: '^/connect/(mellon)$', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/connect/(mellon)/check', role: 'ROLE_USER' }
        - { path: '^/', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
