security:
    providers:
        short_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: '^/'
            guard:
                authenticators:
                    - app_guard_authenticator
            logout:
                path: '/logout'
                target: '/'
                success_handler: App\Security\Guard\GuardLogoutSuccesHandler
            anonymous: true
            switch_user: true

    access_control:
        - { path: '^/manage/admin', role: 'ROLE_ADMIN' }
        - { path: '^/manage', role: 'ROLE_USER' }
        - { path: '^/connect/(mellon|inacademia)$', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/connect/(mellon|inacademia)/', role: 'ROLE_USER' }
        - { path: '^/', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
