security:
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: id

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: '^/'
            user_checker: App\Security\UserChecker
            guard:
                authenticators:
                    - app_guard_authenticator
            logout:
                path: '/logout'
                target: '/'
            anonymous: true
            switch_user: true

    access_control:
        - { path: '^/admin', role: 'ROLE_ADMIN' }
        - { path: '^/manage/admin', role: 'ROLE_ADMIN' }
        - { path: '^/manage', role: 'ROLE_USER' }
        - { path: '^/connect/(mellon|oidc)', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/connect/mellon/return$', methods: ['GET'], role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/connect/(mellon|oidc)/', role: 'ROLE_USER' }
        - { path: '^/', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
