security:
    enable_authenticator_manager: true

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: id

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            host: '%app.urldomain%'
            pattern: '^/'
            user_checker: App\Security\UserChecker
            guard:
                authenticators:
                    - app_guard_authenticator
            logout:
                path: '/logout'
                target: '/'
            switch_user: true
            login_link:
                check_route: login_check
                #max_uses: 1
                used_link_cache: cache.app
                signature_properties: [ 'id' ]
            provider: app_user_provider

        institutional:
            pattern: '^/'
            user_checker: App\Security\UserChecker
            lazy: true
            login_link:
                check_route: login_check
                #max_uses: 1
                used_link_cache: cache.app
                signature_properties: [ 'id' ]
            provider: app_user_provider

    access_control:
        - { path: '^/admin', role: 'ROLE_ADMIN' }
        - { path: '^/manage/admin', role: 'ROLE_ADMIN' }
        - { path: '^/manage', role: 'ROLE_USER' }
        - { path: '^/connect/(mellon|oidc)', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/connect/mellon/return$', methods: ['GET'], role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/connect/(mellon|oidc)/', role: 'ROLE_USER' }
        - { path: '^/', role: 'PUBLIC_ACCESS' }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
