twig:
    form_themes: ['bootstrap_4_layout.html.twig']

    default_path: '%kernel.project_dir%/templates'

    globals:
        APP_NAME: '%app.name%'
        APP_URLDOMAIN: '%app.urldomain%'
        APP_BASEDOMAIN: '%app.protocol%://%app.urldomain%'
        APP_PAYOFF: '%app.payoff%'
        APP_IDP_NAME: '%app.idp_name%'
