connect_openidc_return:
    path: "/connect/oidc/return"
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template: 'security/oidc.html.twig'

connect_openidc_check:
    path: "/connect/oidc/return"
    controller: App\Controller\Security\InAcademiaCheckController
    methods: POST

connect_openidc_start:
    path: "/connect/oidc"
    defaults:
        _controller: App\Controller\Security\InAcademiaStartController
