connect_openidc_return:
    host: "{domain}"
    path: "/connect/oidc/return"
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template: 'security/oidc.html.twig'
        domain: '%app.urldomain%'
    requirements:
        domain: '%app.urldomain%'

connect_openidc_check:
    host: "{domain}"
    path: "/connect/oidc/return"
    controller: App\Controller\Security\InAcademiaCheckController
    methods: POST
    defaults:
        domain: '%app.urldomain%'
    requirements:
        domain: '%app.urldomain%'

connect_openidc_start:
    host: "{domain}"
    path: "/connect/oidc"
    controller: App\Controller\Security\InAcademiaStartController
    defaults:
        domain: '%app.urldomain%'
    requirements:
        domain: '%app.urldomain%'

login_check:
    path: "/login_check"
    defaults:
        _controller: App\Controller\Security\LoginLinkCheckController

login_link:
    path: "/login_link"
    defaults:
        _controller: App\Controller\Security\LoginLinkController

logout:
    path: /logout
